---
- name: Install Apache
  hosts: all
  become: yes

  tasks:
  - name: install Apache
    apt:
      name: apache2
      state: latest

  - name: start Apache and enable
    service:
      name: apache2
      state: started
      enabled: yes
